import { Track } from '../interfaces/track.interface';

export const TRACKS: Track[] = [

  {
    slug: 'fullstack-1',
    title: 'Fullstack 1',
    technologies: [
      'HTML',
      'CSS',
      'SCSS',
      'JavaScript',
      'React',
      'React Native',
      'Node.js',
      'MongoDB',
      'Git',
      'GitHub',
      'ChatGPT',
    ],
    courses: [
      'PLpdAy0tYrnKy78lFgG55BL2RfVw9hB-je',
      'PLaLQ4gJXUd6B45ASQfyr5K-qSNNQIwtqf',
      'PLbCB1B9Iob37xNwkfcU6p-VRTQJD_Nxii',
      'PLx4x_zx8csUg_AxxbVWHEyAJ6cBdsYc0T',
      'PLnDvRpP8BneyVA0SZ2okm-QBojomniQVO',
      'PLdDT8if5attEd4sRnZBIkNihR-_tE612_',
      'PLJ_KhUnlXUPtbtLwaxxUxHqvcNQndmI4B',
      'PL4OAe-tL47sZeAX1LXxSZxXtqj1fYGkF1',
      'PLpaKFn4Q4GMOhOuffvi7VagNib0P325AV',
      'PLygIEirBzJi5PB0OPSsKuAkP7LgNSxEtG',
      'PLlSoD8PAohqSWyUQsyXgwxMiX48_SFDC1',
    ],
  },

  {
    slug: 'fullstack-2',
    title: 'Fullstack 2',
    technologies: [
      'HTML',
      'CSS',
      'Styled Components',
      'TypeScript',
      'React',
      'React Native',
      'Python',
      'MySQL',
      'AWS',
      'Docker',
      'ChatGPT',
    ],
    courses: [
      'PLwgL9IEA0PxUjbhob9UMdpVq12sGrjgU6',
      'PLirko8T4cEmzrH3jIJi7R7ufeqcpXYaLa',
      'PL7zl8TDRnbulsGX8znjV0SA1cDBVzCwga',
      'PLlAbYrWSYTiPanrzauGa7vMuve7_vnXG_',
      'PLnex8IkmReXyNgtea8ly0Pn7Kk7Kavn9v',
      'PL29TaWXah3ibI0ewWkI7xMI952wHEaFTK',
      'PL5TJqBvpXQv55oh1fRrBol4LSKEqUbVD0',
      'PLbIBj8vQhvm2WT-pjGS5x7zUzmh4VgvRk',
      'PLK2b5y9F1DqaTWBrcxKMdwChTOAOBiksx',
      'PLf-O3X2-mxDn1VpyU2q3fuI6YYeIWp5rR',
      'PLltHgIJnfTsAraUYcKaW3cgnU_AiTFRfT',
    ],
  },

  {
    slug: 'fullstack-3',
    title: 'Fullstack 3',
    technologies: [
      'HTML',
      'CSS',
      'Tailwind',
      'JavaScript',
      'Vue',
      'Java',
      'SQL Server',
      'Azure',
      'CI/CD',
      'ChatGPT',
    ],
    courses: [
      'PLpdAy0tYrnKwmcenKePWr9TQ9deRanAr7',
      'PLnDvRpP8Bnez2LJGshXKtid2f-aUkFOqM',
      'PLGFwuV_B-U2W263p_tKmLo51O32sCdtiC',
      'PLsFVybaG4mODFwCuV06yLitVTikKF09sy',
      'PLcoYAcR89n-qq1vGRbaUiV6Q9puy0qigW',
      'PLNCSWIsR6ADI_wMAx9F-Iu8Hs9HHxj4sb',
      'PLLbQNZHBOJtZ1oAbve_kacS5nm9u1ULou',
      'PLj8JhcdUB95awioM24Os3__p4dakaQBm3',
      'PLy7NrYWoggjzSIlwxeBbcgfAdYoxCIrM2',
      'PLgheMYmm7jDvFs01QSNnLvZMIDbliAiMD',
    ],
  },

  {
    slug: 'fullstack-4',
    title: 'Fullstack 4',
    technologies: [
      'HTML',
      'CSS',
      'Bootstrap',
      'JavaScript',
      'Angular',
      '.NET',
      'PostgreSQL',
      'Git',
      'GitHub',
      'DeepSeek',
    ],
    courses: [
      'PLMbclvogjXZWgHgQcY5H4MvKtEW8q53cC',
      'PLYgzkrmJnLwpeeGgdADYq3cE2yUwLLTOv',
      'PLnDvRpP8Bnexu5wvxogy6N49_S5Xk8Cze',
      'PLHz_AreHm4dlsK3Nr9GVvXCbpQyHQl1o1',
      'PLNCSWIsR6ADJuQd4x6LVIC4VFMYArdg3M',
      'PLrRv4QVZ0x89OAocTrL9JzaDZ6U4nzLRN',
      'PLDqAb8tE7SQZzMWvPG4PYevQAW1cDsbD0',
      'PLucm8g_ezqNq0dOgug6paAkH0AQSJPlIe',
      'PLvlkVRRKOYFQyKmdrassLNxkzSMM6tcSL',
      'PLKn8rrZ5ziJU9qwKYYcq0qGd_c-a6laNn',
    ],
  },

  {
    slug: 'fullstack-5',
    title: 'Fullstack 5',
    technologies: [
      'HTML',
      'CSS',
      'SCSS',
      'TypeScript',
      'Angular',
      'Flutter',
      'Node.js',
      'NestJS',
      'MongoDB',
      'Docker',
      'Kubernetes',
      'ChatGPT',
    ],
    courses: [
      'PLa3uqHCcweThO0Cv_Ogrj-WSqluotKm5s',
      'PLhSj3UTs2_yU0fGoS1bjpHqky4kCEmTbR',
      'PLMy95_4XE08OmaSd_GOLKNkqhoJFvg7w7',
      'PL62G310vn6nGg5OzjxE8FbYDzCs_UqrUs',
      'PLGxZ4Rq3BOBoSRcKWEdQACbUCNWLczg2G',
      'PLqdwHeoSjEN-9aGd-RxaS_2cyD_AKT0c_',
      'PLnDvRpP8BneyHealXbzntUoFtE4SrFWWW',
      'PLhqYZdo-g9iR9AcfOxiU_6TQE2M5lY1ZT',
      'PLOqGgazdqtt1_B_IwOqWAssif-E410N58',
      'PLNCSWIsR6ADKRq-XBvAcRd4XtqLj3f_mf',
      'PL9wKVHxY5DoNy-D4errvry9sVktl9YNcA',
      'PLH4wYtX2PQNFPU8FdbGbJIzenVdyaIf6T',
    ],
  },

  {
    slug: 'frontend-1',
    title: 'Frontend 1',
    technologies: [
      'HTML',
      'CSS',
      'Tailwind',
      'JavaScript',
      'React',
      'React Native',
      'Git',
      'Kubernetes',
      'ChatGPT',
    ],
    courses: [
      'PLhSj3UTs2_yVHt2DgHky_MzzRC58UHE4z',
      'PL1dUY2RYa2RhNhm-QTuNIifVpc59wrpFP',
      'PL_m43UlJFjF5umRjQW1eaLgJmsEpF_Q2E',
      'PL2Fdisxwzt_d590u3uad46W-kHA0PTjjw',
      'PL29TaWXah3iaqOejItvW--TaFr9NcruyQ',
      'PLRGv4LGMjiB9nBoDXNR19CiOft3fW0ald',
      'PLcoYAcR89n-qbO7YAVj5S0alABLis_QVU',
      'PLnOICPAPShyTwuLit7vP6In9kETQ0BSnQ',
      'PLFKhhNd35zq9mbam1QMKnWhLbvjnBgp88',
    ],
  },

  {
    slug: 'frontend-2',
    title: 'Frontend 2',
    technologies: [
      'HTML',
      'CSS',
      'Styled Components',
      'TypeScript',
      'Angular',
      'Flutter',
      'Git',
      'GitHub',
      'ChatGPT',
    ],
    courses: [
      'PLbIBj8vQhvm00J3f3rD33tRuNLem8EgEA',
      'PLsFVybaG4mOAXJTzysk9-d3OeROyWhhvs',
      'PL6tdbGPF9i1VqSQjWjQQ3HCprLVHsw4rJ',
      'PLyugqHiq-SKe_waUyoJIA60-OuBeVOtx0',
      'PLhna1crYw0SOFqiss05ybqJCc6fvGn6BF',
      'PL5EmR7zuTn_Yu_YV2pT0h0843vRGiTMtx',
      'PLHz_AreHm4dm7ZULPAmadvNhH6vk9oNZA',
      'PLMFPOLE2cW1yu-FfYiGElIrDqQfKmZGLM',
      'PLgkBVJFsrrYK8ZbUWYQ5hSFK-VgKoGohF',
    ],
  },

  {
    slug: 'frontend-3',
    title: 'Frontend 3',
    technologies: [
      'HTML',
      'CSS',
      'SCSS',
      'TypeScript',
      'Vue',
      'Flutter',
      'GitHub',
      'AWS',
      'ChatGPT',
    ],
    courses: [
      'PL2Fdisxwzt_cajoGVWTx44wM6Ht09QJ3A',
      'PL2Fdisxwzt_f5C7Mv0kg1EAHhy2VJLf1c',
      'PL97KElaimHeGRtfkksKwxg6IGVZi_cR7J',
      'PLx4x_zx8csUhtPMrkiGvFJVE5LX8Qat5s',
      'PLnDvRpP8BnezDglaAvtWgQXzsOmXUuRHL',
      'PLRpTFz5_57cvJyGFOD-Jx_cYqc1t2Wjk1',
      'PLygIEirBzJi4kZyRNTtBE3KC99qEOmyjl',
      'PLOF5f9_x-OYUaqJar6EKRAonJNSHDFZUm',
      'PL1xAElQrK4BLfBKcccBqYOCIn1A7Jz-FU',
    ],
  },

  {
    slug: 'backend-1',
    title: 'Backend 1',
    technologies: [
      'Node.js',
      'NestJS',
      'MySQL',
      'Docker',
      'Azure',
      'CI/CD',
      'ChatGPT',
    ],
    courses: [
      'PLx4x_zx8csUjFC41ev2qX5dnr-0ThpoXE',
      'PLpcf8hdkpCYseV2ctwAhE4dY-AQ7v5D9S',
      'PLO5rsoBNVkNonB8L7XDZPW_iDzSAyswjZ',
      'PLXzx948cNtr8N5zLNJNVYrvIG6hk0Kxl-',
      'PLz3hnOImntANgM1EyWSGkY4v-7dhWURWt',
      'PLVx1qovxj-am2q9M8mC2CmMUfrxZGoZ9J',
      'PL7iAT8C5wumoJhaDVIz49POISoaJ2OFep',
    ],
  },

  {
    slug: 'backend-2',
    title: 'Backend 2',
    technologies: [
      'Python',
      'SQL Server',
      'Docker',
      'AWS',
      'CI/CD',
      'DeepSeek',
    ],
    courses: [
      'PLpaKFn4Q4GMN1A4J1FnhW_anOGt8ug8ip',
      'PL4OAe-tL47sY7ZzeE8__q_N7BWFOehxug',
      'PLx4x_zx8csUghdJDl3jbRYDr4FJ5y2o8-',
      'PLtL97Owd1gkQ0dfqGW8OtJ-155Gs67Ecz',
      'PLB2SqGllEo-WcgoHuhCfFVX2NOMXgOhRJ',
      'PL18bbNo7xuh-2lshEXKsz0rKO9qLFbgrp',
    ],
  },

  {
    slug: 'backend-3',
    title: 'Backend 3',
    technologies: [
      'Java',
      'PostgreSQL',
      'Kubernetes',
      'CI/CD',
      'Azure',
      'ChatGPT',
    ],
    courses: [
      'PL62G310vn6nFIsOCC0H-C2infYgwm8SWW',
      'PL2hDwB8DzXGP-pMRJUsg-yPGwZ_TheEgA',
      'PLXzx948cNtr8XI5JBemHT9OWuYSPNUtXs',
      'PLZ4jpQqTamn0QMqdKdgBAH4zUtOxJne50',
      'PLMFPOLE2cW1yXGKZ6Mt12P1ewsmmgRQTk',
      'PLHz_AreHm4dm24MhlWJYiR_Rm7TFtvs6S',
    ],
  },

];